development:
  adapter: postgresql
  encoding: unicode
  database: ember-tutorial_development
  password: 4373
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ember-tutorial_test
  password: 4373
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ember-tutorial_production
  password: 4373
  host: localhost
